package com.example.sonara.domain.lyrics

/**
 * Pure Kotlin Brahmic-to-IAST transliterator for Indic scripts.
 * Emulates Sanscript transliterateBrahmic mapping for Devanagari, Bengali, Gurmukhi,
 * Gujarati, Tamil, Telugu, Kannada, and Malayalam.
 */
object BrahmicToIast {

    private class ScriptMap(
        val marks: Map<Char, String>,
        val letters: Map<Char, String>,
        val consonants: Set<Char>
    )

    private val maps: Map<String, ScriptMap> by lazy {
        mapOf(
            "devanagari" to ScriptMap(
                marks = mapOf(
                    'ा' to "ā",
                    'ि' to "i",
                    'ी' to "ī",
                    'ु' to "u",
                    'ू' to "ū",
                    'ृ' to "ṛ",
                    'ॄ' to "ṝ",
                    'ॢ' to "ḷ",
                    'ॣ' to "ḹ",
                    'ॆ' to "è",
                    'े' to "e",
                    'ै' to "ai",
                    'ॊ' to "ò",
                    'ो' to "o",
                    'ौ' to "au",
                    'ॅ' to "e",
                    'ॉ' to "o",
                    '्' to "",
                ),
                letters = mapOf(
                    'अ' to "a",
                    'आ' to "ā",
                    'इ' to "i",
                    'ई' to "ī",
                    'उ' to "u",
                    'ऊ' to "ū",
                    'ऋ' to "ṛ",
                    'ॠ' to "ṝ",
                    'ऌ' to "ḷ",
                    'ॡ' to "ḹ",
                    'ऎ' to "è",
                    'ए' to "e",
                    'ऐ' to "ai",
                    'ऒ' to "ò",
                    'ओ' to "o",
                    'औ' to "au",
                    'ऍ' to "e",
                    'ऑ' to "o",
                    'ं' to "ṃ",
                    'ः' to "ḥ",
                    'ँ' to "~",
                    'ꣳ' to "m̐",
                    'क' to "k",
                    'ख' to "kh",
                    'ग' to "g",
                    'घ' to "gh",
                    'ङ' to "ṅ",
                    'च' to "c",
                    'छ' to "ch",
                    'ज' to "j",
                    'झ' to "jh",
                    'ञ' to "ñ",
                    'ट' to "ṭ",
                    'ठ' to "ṭh",
                    'ड' to "ḍ",
                    'ढ' to "ḍh",
                    'ण' to "ṇ",
                    'त' to "t",
                    'थ' to "th",
                    'द' to "d",
                    'ध' to "dh",
                    'न' to "n",
                    'प' to "p",
                    'फ' to "ph",
                    'ब' to "b",
                    'भ' to "bh",
                    'म' to "m",
                    'य' to "y",
                    'र' to "r",
                    'ल' to "l",
                    'व' to "v",
                    'श' to "ś",
                    'ष' to "ṣ",
                    'स' to "s",
                    'ह' to "h",
                    'ळ' to "l̤",
                    '०' to "0",
                    '१' to "1",
                    '२' to "2",
                    '३' to "3",
                    '४' to "4",
                    '५' to "5",
                    '६' to "6",
                    '७' to "7",
                    '८' to "8",
                    '९' to "9",
                    'ॐ' to "oṃ",
                    'ऽ' to "'",
                    '।' to "|",
                    '॥' to "||",
                    '॑' to "̭",
                    '॒' to "॒",
                    '᳡' to "̀",
                    '꣡' to "́",
                    '꣢' to "²",
                    '꣣' to "³",
                    '꣤' to "⁴",
                    '꣥' to "⁵",
                    '꣦' to "⁶",
                    '꣧' to "⁷",
                    '꣨' to "⁸",
                    '꣩' to "⁹",
                    '꣪' to "꣪",
                    '꣫' to "꣫",
                    '꣬' to "꣬",
                    '꣭' to "꣭",
                    '꣮' to "꣮",
                    '꣯' to "꣯",
                    '꣰' to "꣰",
                    '꣱' to "꣱",
                    'क़' to "q",
                    'ख़' to "kh",
                    'ग़' to "gh",
                    'ज़' to "z",
                    'ड़' to "r̤",
                    'ढ़' to "r̤h",
                    'फ़' to "f",
                    'य़' to "ẏ",
                    'ऱ' to "ṟ",
                    'ऴ' to "ḻ",
                    'ऩ' to "ṉ",
                ),
                consonants = setOf(
                    'ख़',
                    'ग़',
                    'ढ़',
                    'ग',
                    'क़',
                    'छ',
                    'ज़',
                    'ऩ',
                    'ळ',
                    'फ़',
                    'घ',
                    'ड',
                    'ढ',
                    'ट',
                    'ष',
                    'ब',
                    'ज',
                    'ण',
                    'ल',
                    'म',
                    'द',
                    'झ',
                    'व',
                    'ह',
                    'य',
                    'य़',
                    'थ',
                    'न',
                    'ख',
                    'भ',
                    'च',
                    'ञ',
                    'प',
                    'ग़',
                    'फ',
                    'ख़',
                    'ड़',
                    'ठ',
                    'ऱ',
                    'र',
                    'क',
                    'ध',
                    'ङ',
                    'ऴ',
                    'स',
                    'श',
                    'त',
                )
            ),
            "bengali" to ScriptMap(
                marks = mapOf(
                    'া' to "ā",
                    'ি' to "i",
                    'ী' to "ī",
                    'ু' to "u",
                    'ূ' to "ū",
                    'ৃ' to "ṛ",
                    'ৄ' to "ṝ",
                    'ৢ' to "ḷ",
                    'ৣ' to "ḹ",
                    'ॆ' to "è",
                    'ে' to "e",
                    'ৈ' to "ai",
                    'ॊ' to "ò",
                    'ো' to "o",
                    'ৌ' to "au",
                    '্' to "",
                ),
                letters = mapOf(
                    'অ' to "a",
                    'আ' to "ā",
                    'ই' to "i",
                    'ঈ' to "ī",
                    'উ' to "u",
                    'ঊ' to "ū",
                    'ঋ' to "ṛ",
                    'ৠ' to "ṝ",
                    'ঌ' to "ḷ",
                    'ৡ' to "ḹ",
                    'ऎ' to "è",
                    'এ' to "e",
                    'ঐ' to "ai",
                    'ऒ' to "ò",
                    'ও' to "o",
                    'ঔ' to "au",
                    'ং' to "ṃ",
                    'ঃ' to "ḥ",
                    'ঁ' to "~",
                    'ক' to "k",
                    'খ' to "kh",
                    'গ' to "g",
                    'ঘ' to "gh",
                    'ঙ' to "ṅ",
                    'চ' to "c",
                    'ছ' to "ch",
                    'জ' to "j",
                    'ঝ' to "jh",
                    'ঞ' to "ñ",
                    'ট' to "ṭ",
                    'ঠ' to "ṭh",
                    'ড' to "ḍ",
                    'ঢ' to "ḍh",
                    'ণ' to "ṇ",
                    'ত' to "t",
                    'থ' to "th",
                    'দ' to "d",
                    'ধ' to "dh",
                    'ন' to "n",
                    'প' to "p",
                    'ফ' to "ph",
                    'ব' to "v",
                    'ভ' to "bh",
                    'ম' to "m",
                    'য' to "y",
                    'র' to "r",
                    'ল' to "l",
                    'শ' to "ś",
                    'ষ' to "ṣ",
                    'স' to "s",
                    'হ' to "h",
                    '০' to "0",
                    '১' to "1",
                    '২' to "2",
                    '৩' to "3",
                    '৪' to "4",
                    '৫' to "5",
                    '৬' to "6",
                    '৭' to "7",
                    '৮' to "8",
                    '৯' to "9",
                    'ঽ' to "'",
                    '।' to "|",
                    '॥' to "||",
                    '॑' to "̭",
                    '॒' to "॒",
                    'ড়' to "r̤",
                    'ঢ়' to "r̤h",
                    'য়' to "ẏ",
                    'ৎ' to "t",
                ),
                consonants = setOf(
                    'খ',
                    'জ',
                    'দ',
                    'ফ',
                    'ছ',
                    'র',
                    'ব',
                    'ত',
                    'ড',
                    'ম',
                    'ঞ',
                    'ধ',
                    'গ',
                    'য়',
                    'স',
                    'চ',
                    'য',
                    'ষ',
                    'হ',
                    'ল',
                    'ট',
                    'ঘ',
                    'ঝ',
                    'ঢ',
                    'ভ',
                    'ণ',
                    'ড়',
                    'প',
                    'ঢ়',
                    'থ',
                    'ঠ',
                    'শ',
                    'ন',
                    'ক',
                    'ঙ',
                )
            ),
            "gurmukhi" to ScriptMap(
                marks = mapOf(
                    'ਾ' to "ā",
                    'ਿ' to "i",
                    'ੀ' to "ī",
                    'ੁ' to "u",
                    'ੂ' to "ū",
                    'ੇ' to "e",
                    'ੈ' to "ai",
                    'ੋ' to "o",
                    'ੌ' to "au",
                    '੍' to "",
                ),
                letters = mapOf(
                    'ਅ' to "a",
                    'ਆ' to "ā",
                    'ਇ' to "i",
                    'ਈ' to "ī",
                    'ਉ' to "u",
                    'ਊ' to "ū",
                    'ਏ' to "e",
                    'ਐ' to "ai",
                    'ਓ' to "o",
                    'ਔ' to "au",
                    'ਂ' to "ṃ",
                    'ੰ' to "ṃ",
                    'ਃ' to "ḥ",
                    'ਁ' to "~",
                    'ਕ' to "k",
                    'ਖ' to "kh",
                    'ਗ' to "g",
                    'ਘ' to "gh",
                    'ਙ' to "ṅ",
                    'ਚ' to "c",
                    'ਛ' to "ch",
                    'ਜ' to "j",
                    'ਝ' to "jh",
                    'ਞ' to "ñ",
                    'ਟ' to "ṭ",
                    'ਠ' to "ṭh",
                    'ਡ' to "ḍ",
                    'ਢ' to "ḍh",
                    'ਣ' to "ṇ",
                    'ਤ' to "t",
                    'ਥ' to "th",
                    'ਦ' to "d",
                    'ਧ' to "dh",
                    'ਨ' to "n",
                    'ਪ' to "p",
                    'ਫ' to "ph",
                    'ਬ' to "b",
                    'ਭ' to "bh",
                    'ਮ' to "m",
                    'ਯ' to "y",
                    'ਰ' to "r",
                    'ਲ' to "l",
                    'ਵ' to "v",
                    'ਸ਼' to "ś",
                    'ਸ' to "s",
                    'ਹ' to "h",
                    'ਲ਼' to "l̤",
                    '੦' to "0",
                    '੧' to "1",
                    '੨' to "2",
                    '੩' to "3",
                    '੪' to "4",
                    '੫' to "5",
                    '੬' to "6",
                    '੭' to "7",
                    '੮' to "8",
                    '੯' to "9",
                    'ੴ' to "oṃ",
                    'ऽ' to "'",
                    '।' to "|",
                    '॥' to "||",
                    'ਖ਼' to "kh",
                    'ਗ਼' to "gh",
                    'ਜ਼' to "z",
                    'ੜ' to "r̤",
                    'ਫ਼' to "f",
                    'ੑ' to "̭",
                    '॒' to "॒",
                ),
                consonants = setOf(
                    'ਗ਼',
                    'ਢ',
                    'ਖ',
                    'ਘ',
                    'ਖ਼',
                    'ਧ',
                    'ਠ',
                    'ਣ',
                    'ਤ',
                    'ਜ਼',
                    'ਭ',
                    'ਰ',
                    'ਚ',
                    'ੜ',
                    'ਫ਼',
                    'ਗ',
                    'ਡ',
                    'ਮ',
                    'ਪ',
                    'ਸ',
                    'ਸ਼',
                    'ਫ',
                    'ਬ',
                    'ਨ',
                    'ਯ',
                    'ਗ਼',
                    'ਲ',
                    'ਥ',
                    'ਛ',
                    'ਝ',
                    'ਙ',
                    'ਜ',
                    'ਵ',
                    'ਹ',
                    'ਦ',
                    'ਲ਼',
                    'ਞ',
                    'ਕ',
                    'ਟ',
                )
            ),
            "gujarati" to ScriptMap(
                marks = mapOf(
                    'ા' to "ā",
                    'િ' to "i",
                    'ી' to "ī",
                    'ુ' to "u",
                    'ૂ' to "ū",
                    'ૃ' to "ṛ",
                    'ૄ' to "ṝ",
                    'ૢ' to "ḷ",
                    'ૣ' to "ḹ",
                    'ॆ' to "è",
                    'ે' to "e",
                    'ૈ' to "ai",
                    'ॊ' to "ò",
                    'ો' to "o",
                    'ૌ' to "au",
                    '્' to "",
                ),
                letters = mapOf(
                    'અ' to "a",
                    'આ' to "ā",
                    'ઇ' to "i",
                    'ઈ' to "ī",
                    'ઉ' to "u",
                    'ઊ' to "ū",
                    'ઋ' to "ṛ",
                    'ૠ' to "ṝ",
                    'ઌ' to "ḷ",
                    'ૡ' to "ḹ",
                    'ऎ' to "è",
                    'એ' to "e",
                    'ઐ' to "ai",
                    'ऒ' to "ò",
                    'ઓ' to "o",
                    'ઔ' to "au",
                    'ં' to "ṃ",
                    'ઃ' to "ḥ",
                    'ઁ' to "~",
                    'ક' to "k",
                    'ખ' to "kh",
                    'ગ' to "g",
                    'ઘ' to "gh",
                    'ઙ' to "ṅ",
                    'ચ' to "c",
                    'છ' to "ch",
                    'જ' to "j",
                    'ઝ' to "jh",
                    'ઞ' to "ñ",
                    'ટ' to "ṭ",
                    'ઠ' to "ṭh",
                    'ડ' to "ḍ",
                    'ઢ' to "ḍh",
                    'ણ' to "ṇ",
                    'ત' to "t",
                    'થ' to "th",
                    'દ' to "d",
                    'ધ' to "dh",
                    'ન' to "n",
                    'પ' to "p",
                    'ફ' to "ph",
                    'બ' to "b",
                    'ભ' to "bh",
                    'મ' to "m",
                    'ય' to "y",
                    'ર' to "r",
                    'લ' to "l",
                    'વ' to "v",
                    'શ' to "ś",
                    'ષ' to "ṣ",
                    'સ' to "s",
                    'હ' to "h",
                    'ળ' to "l̤",
                    '૦' to "0",
                    '૧' to "1",
                    '૨' to "2",
                    '૩' to "3",
                    '૪' to "4",
                    '૫' to "5",
                    '૬' to "6",
                    '૭' to "7",
                    '૮' to "8",
                    '૯' to "9",
                    'ૐ' to "oṃ",
                    'ઽ' to "'",
                    '।' to "|",
                    '॥' to "||",
                    '॑' to "̭",
                    '॒' to "॒",
                ),
                consonants = setOf(
                    'લ',
                    'ખ',
                    'ળ',
                    'ઠ',
                    'ઝ',
                    'ચ',
                    'ધ',
                    'ઞ',
                    'હ',
                    'થ',
                    'ત',
                    'ય',
                    'ઢ',
                    'છ',
                    'ડ',
                    'ક',
                    'ર',
                    'શ',
                    'ઘ',
                    'ગ',
                    'વ',
                    'જ',
                    'ભ',
                    'ઙ',
                    'ફ',
                    'બ',
                    'મ',
                    'સ',
                    'ષ',
                    'પ',
                    'દ',
                    'ણ',
                    'ટ',
                    'ન',
                )
            ),
            "tamil" to ScriptMap(
                marks = mapOf(
                    'ா' to "ā",
                    'ி' to "i",
                    'ீ' to "ī",
                    'ு' to "u",
                    'ூ' to "ū",
                    'ெ' to "è",
                    'ே' to "e",
                    'ை' to "ai",
                    'ொ' to "ò",
                    'ோ' to "o",
                    'ௌ' to "au",
                    '்' to "",
                ),
                letters = mapOf(
                    'அ' to "a",
                    'ஆ' to "ā",
                    'இ' to "i",
                    'ஈ' to "ī",
                    'உ' to "u",
                    'ஊ' to "ū",
                    'எ' to "è",
                    'ஏ' to "e",
                    'ஐ' to "ai",
                    'ஒ' to "ò",
                    'ஓ' to "o",
                    'ஔ' to "au",
                    'ஃ' to "ḥ",
                    'க' to "gh",
                    'ங' to "ṅ",
                    'ச' to "jh",
                    'ஜ' to "j",
                    'ஞ' to "ñ",
                    'ட' to "ḍh",
                    'ண' to "ṇ",
                    'த' to "dh",
                    'ந' to "n",
                    'ப' to "bh",
                    'ம' to "m",
                    'ய' to "y",
                    'ர' to "r",
                    'ல' to "l",
                    'வ' to "v",
                    'ஶ' to "ś",
                    'ஷ' to "ṣ",
                    'ஸ' to "s",
                    'ஹ' to "h",
                    'ள' to "l̤",
                    '௦' to "0",
                    '௧' to "1",
                    '௨' to "2",
                    '௩' to "3",
                    '௪' to "4",
                    '௫' to "5",
                    '௬' to "6",
                    '௭' to "7",
                    '௮' to "8",
                    '௯' to "9",
                    'ௐ' to "oṃ",
                    'ऽ' to "'",
                    '।' to "|",
                    '॥' to "||",
                    'ற' to "ṟ",
                    'ழ' to "ḻ",
                    'ன' to "ṉ",
                ),
                consonants = setOf(
                    'த',
                    'ட',
                    'ங',
                    'க',
                    'வ',
                    'ன',
                    'ப',
                    'ழ',
                    'ந',
                    'ஸ',
                    'ஷ',
                    'ண',
                    'ர',
                    'ய',
                    'ஶ',
                    'ம',
                    'ற',
                    'ஞ',
                    'ஜ',
                    'ஹ',
                    'ல',
                    'ள',
                    'ச',
                )
            ),
            "telugu" to ScriptMap(
                marks = mapOf(
                    'ా' to "ā",
                    'ి' to "i",
                    'ీ' to "ī",
                    'ు' to "u",
                    'ూ' to "ū",
                    'ృ' to "ṛ",
                    'ౄ' to "ṝ",
                    'ౢ' to "ḷ",
                    'ౣ' to "ḹ",
                    'ె' to "è",
                    'ే' to "e",
                    'ై' to "ai",
                    'ొ' to "ò",
                    'ో' to "o",
                    'ౌ' to "au",
                    '్' to "",
                ),
                letters = mapOf(
                    'అ' to "a",
                    'ఆ' to "ā",
                    'ఇ' to "i",
                    'ఈ' to "ī",
                    'ఉ' to "u",
                    'ఊ' to "ū",
                    'ఋ' to "ṛ",
                    'ౠ' to "ṝ",
                    'ఌ' to "ḷ",
                    'ౡ' to "ḹ",
                    'ఎ' to "è",
                    'ఏ' to "e",
                    'ఐ' to "ai",
                    'ఒ' to "ò",
                    'ఓ' to "o",
                    'ఔ' to "au",
                    'ం' to "ṃ",
                    'ః' to "ḥ",
                    'ఁ' to "~",
                    'క' to "k",
                    'ఖ' to "kh",
                    'గ' to "g",
                    'ఘ' to "gh",
                    'ఙ' to "ṅ",
                    'చ' to "c",
                    'ఛ' to "ch",
                    'జ' to "j",
                    'ఝ' to "jh",
                    'ఞ' to "ñ",
                    'ట' to "ṭ",
                    'ఠ' to "ṭh",
                    'డ' to "ḍ",
                    'ఢ' to "ḍh",
                    'ణ' to "ṇ",
                    'త' to "t",
                    'థ' to "th",
                    'ద' to "d",
                    'ధ' to "dh",
                    'న' to "n",
                    'ప' to "p",
                    'ఫ' to "ph",
                    'బ' to "b",
                    'భ' to "bh",
                    'మ' to "m",
                    'య' to "y",
                    'ర' to "r",
                    'ల' to "l",
                    'వ' to "v",
                    'శ' to "ś",
                    'ష' to "ṣ",
                    'స' to "s",
                    'హ' to "h",
                    'ళ' to "l̤",
                    '౦' to "0",
                    '౧' to "1",
                    '౨' to "2",
                    '౩' to "3",
                    '౪' to "4",
                    '౫' to "5",
                    '౬' to "6",
                    '౭' to "7",
                    '౮' to "8",
                    '౯' to "9",
                    'ఽ' to "'",
                    '।' to "|",
                    '॥' to "||",
                    'ఱ' to "ṟ",
                    'ఴ' to "ḻ",
                ),
                consonants = setOf(
                    'ఛ',
                    'య',
                    'ఘ',
                    'థ',
                    'ద',
                    'ళ',
                    'ఙ',
                    'భ',
                    'ఖ',
                    'ఴ',
                    'గ',
                    'డ',
                    'ఫ',
                    'స',
                    'ట',
                    'ఱ',
                    'క',
                    'ణ',
                    'ఠ',
                    'ల',
                    'ర',
                    'వ',
                    'ఞ',
                    'హ',
                    'జ',
                    'ప',
                    'బ',
                    'చ',
                    'శ',
                    'త',
                    'న',
                    'ష',
                    'ఢ',
                    'ఝ',
                    'ధ',
                    'మ',
                )
            ),
            "kannada" to ScriptMap(
                marks = mapOf(
                    'ಾ' to "ā",
                    'ಿ' to "i",
                    'ೀ' to "ī",
                    'ು' to "u",
                    'ೂ' to "ū",
                    'ೃ' to "ṛ",
                    'ೄ' to "ṝ",
                    'ೢ' to "ḷ",
                    'ೣ' to "ḹ",
                    'ೆ' to "è",
                    'ೇ' to "e",
                    'ೈ' to "ai",
                    'ೊ' to "ò",
                    'ೋ' to "o",
                    'ೌ' to "au",
                    '್' to "",
                ),
                letters = mapOf(
                    'ಅ' to "a",
                    'ಆ' to "ā",
                    'ಇ' to "i",
                    'ಈ' to "ī",
                    'ಉ' to "u",
                    'ಊ' to "ū",
                    'ಋ' to "ṛ",
                    'ೠ' to "ṝ",
                    'ಌ' to "ḷ",
                    'ೡ' to "ḹ",
                    'ಎ' to "è",
                    'ಏ' to "e",
                    'ಐ' to "ai",
                    'ಒ' to "ò",
                    'ಓ' to "o",
                    'ಔ' to "au",
                    'ಂ' to "ṃ",
                    'ಃ' to "ḥ",
                    'ಁ' to "~",
                    'ಕ' to "k",
                    'ಖ' to "kh",
                    'ಗ' to "g",
                    'ಘ' to "gh",
                    'ಙ' to "ṅ",
                    'ಚ' to "c",
                    'ಛ' to "ch",
                    'ಜ' to "j",
                    'ಝ' to "jh",
                    'ಞ' to "ñ",
                    'ಟ' to "ṭ",
                    'ಠ' to "ṭh",
                    'ಡ' to "ḍ",
                    'ಢ' to "ḍh",
                    'ಣ' to "ṇ",
                    'ತ' to "t",
                    'ಥ' to "th",
                    'ದ' to "d",
                    'ಧ' to "dh",
                    'ನ' to "n",
                    'ಪ' to "p",
                    'ಫ' to "ph",
                    'ಬ' to "b",
                    'ಭ' to "bh",
                    'ಮ' to "m",
                    'ಯ' to "y",
                    'ರ' to "r",
                    'ಲ' to "l",
                    'ವ' to "v",
                    'ಶ' to "ś",
                    'ಷ' to "ṣ",
                    'ಸ' to "s",
                    'ಹ' to "h",
                    'ಳ' to "l̤",
                    '೦' to "0",
                    '೧' to "1",
                    '೨' to "2",
                    '೩' to "3",
                    '೪' to "4",
                    '೫' to "5",
                    '೬' to "6",
                    '೭' to "7",
                    '೮' to "8",
                    '೯' to "9",
                    'ಽ' to "'",
                    '।' to "|",
                    '॥' to "||",
                    'ಱ' to "ṟ",
                    'ೞ' to "ḻ",
                ),
                consonants = setOf(
                    'ಫ',
                    'ನ',
                    'ಯ',
                    'ಖ',
                    'ವ',
                    'ಥ',
                    'ಲ',
                    'ಗ',
                    'ಕ',
                    'ಸ',
                    'ಛ',
                    'ೞ',
                    'ಜ',
                    'ಣ',
                    'ಢ',
                    'ಳ',
                    'ಡ',
                    'ಝ',
                    'ತ',
                    'ಪ',
                    'ಭ',
                    'ಘ',
                    'ಟ',
                    'ಹ',
                    'ದ',
                    'ಬ',
                    'ಞ',
                    'ಧ',
                    'ಮ',
                    'ರ',
                    'ಙ',
                    'ಶ',
                    'ಱ',
                    'ಠ',
                    'ಚ',
                    'ಷ',
                )
            ),
            "malayalam" to ScriptMap(
                marks = mapOf(
                    'ാ' to "ā",
                    'ി' to "i",
                    'ീ' to "ī",
                    'ു' to "u",
                    'ൂ' to "ū",
                    'ൃ' to "ṛ",
                    'ൄ' to "ṝ",
                    'ൢ' to "ḷ",
                    'ൣ' to "ḹ",
                    'െ' to "è",
                    'േ' to "e",
                    'ൈ' to "ai",
                    'ൊ' to "ò",
                    'ോ' to "o",
                    'ൌ' to "au",
                    '്' to "",
                ),
                letters = mapOf(
                    'അ' to "a",
                    'ആ' to "ā",
                    'ഇ' to "i",
                    'ഈ' to "ī",
                    'ഉ' to "u",
                    'ഊ' to "ū",
                    'ഋ' to "ṛ",
                    'ൠ' to "ṝ",
                    'ഌ' to "ḷ",
                    'ൡ' to "ḹ",
                    'എ' to "è",
                    'ഏ' to "e",
                    'ഐ' to "ai",
                    'ഒ' to "ò",
                    'ഓ' to "o",
                    'ഔ' to "au",
                    'ം' to "ṃ",
                    'ഃ' to "ḥ",
                    'ഁ' to "~",
                    'ക' to "k",
                    'ഖ' to "kh",
                    'ഗ' to "g",
                    'ഘ' to "gh",
                    'ങ' to "ṅ",
                    'ച' to "c",
                    'ഛ' to "ch",
                    'ജ' to "j",
                    'ഝ' to "jh",
                    'ഞ' to "ñ",
                    'ട' to "ṭ",
                    'ഠ' to "ṭh",
                    'ഡ' to "ḍ",
                    'ഢ' to "ḍh",
                    'ണ' to "ṇ",
                    'ത' to "t",
                    'ഥ' to "th",
                    'ദ' to "d",
                    'ധ' to "dh",
                    'ന' to "n",
                    'പ' to "p",
                    'ഫ' to "ph",
                    'ബ' to "b",
                    'ഭ' to "bh",
                    'മ' to "m",
                    'യ' to "y",
                    'ര' to "r",
                    'ല' to "l",
                    'വ' to "v",
                    'ശ' to "ś",
                    'ഷ' to "ṣ",
                    'സ' to "s",
                    'ഹ' to "h",
                    'ള' to "l̤",
                    '൦' to "0",
                    '൧' to "1",
                    '൨' to "2",
                    '൩' to "3",
                    '൪' to "4",
                    '൫' to "5",
                    '൬' to "6",
                    '൭' to "7",
                    '൮' to "8",
                    '൯' to "9",
                    'ഽ' to "'",
                    '।' to "|",
                    '॥' to "||",
                    'റ' to "ṟ",
                    'ഴ' to "ḻ",
                ),
                consonants = setOf(
                    'ഥ',
                    'പ',
                    'ഘ',
                    'ര',
                    'ഭ',
                    'ണ',
                    'ഷ',
                    'ദ',
                    'ഞ',
                    'ഴ',
                    'വ',
                    'ച',
                    'ഛ',
                    'ജ',
                    'ബ',
                    'മ',
                    'സ',
                    'ഹ',
                    'ല',
                    'റ',
                    'ട',
                    'ഗ',
                    'ഢ',
                    'ഖ',
                    'ഡ',
                    'ഝ',
                    'ധ',
                    'ത',
                    'ഫ',
                    'ക',
                    'യ',
                    'ള',
                    'ശ',
                    'ഠ',
                    'ന',
                    'ങ',
                )
            ),
        )
    }

    private val NUKTAS = setOf('\u093C', '\u09BC', '\u0A3C', '\u0ABC')

    fun transliterate(data: String, scriptName: String): String {
        val map = maps[scriptName] ?: return data
        val buf = StringBuilder()
        val consonants = map.consonants
        val letters = map.letters
        val marks = map.marks
        var hadRomanConsonant = false

        for (i in data.indices) {
            val char = data[i]
            val mark = marks[char]
            if (mark != null) {
                buf.append(mark)
                hadRomanConsonant = false
            } else if (char in NUKTAS) {
                buf.append(char)
            } else {
                if (hadRomanConsonant) {
                    buf.append('a')
                    hadRomanConsonant = false
                }
                val letter = letters[char]
                if (letter != null) {
                    buf.append(letter)
                    hadRomanConsonant = char in consonants
                } else {
                    buf.append(char)
                }
            }
        }

        if (hadRomanConsonant) {
            buf.append('a')
        }

        return buf.toString()
    }
}
